apiVersion: v1
kind: Service
metadata:
  name: filevault-frontend-service
spec:
  type: NodePort
  selector:
    app: filevault-frontend
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30000
